// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChangesTag: typeof import('./src/components/ChangesTag.vue')['default']
    CompareSelector: typeof import('./src/components/CompareSelector.vue')['default']
    ICarbonCaretDown: typeof import('~icons/carbon/caret-down')['default']
    ICarbonCaretUp: typeof import('~icons/carbon/caret-up')['default']
    ICarbonOverflowMenuHorizontal: typeof import('~icons/carbon/overflow-menu-horizontal')['default']
    ICarbonUser: typeof import('~icons/carbon/user')['default']
    MajorChart: typeof import('./src/components/MajorChart.vue')['default']
    MajorChips: typeof import('./src/components/MajorChips.vue')['default']
    MajorSelector: typeof import('./src/components/MajorSelector.vue')['default']
    MajorStatistic: typeof import('./src/components/MajorStatistic.vue')['default']
    MajorTableSummary: typeof import('./src/components/MajorTableSummary.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCol: typeof import('naive-ui')['NCol']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NResult: typeof import('naive-ui')['NResult']
    NRow: typeof import('naive-ui')['NRow']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NTag: typeof import('naive-ui')['NTag']
    NTime: typeof import('naive-ui')['NTime']
    NWatermark: typeof import('naive-ui')['NWatermark']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    UniversityChips: typeof import('./src/components/UniversityChips.vue')['default']
    UniversitySelector: typeof import('./src/components/UniversitySelector.vue')['default']
    UniversityStatistic: typeof import('./src/components/UniversityStatistic.vue')['default']
  }
}

export { }
